Repository cloudquery/cq-provider-aws, pull requests merged in 2022-02, with the labels that each got.

#463 fix: Remove stray tab from awsFailedToConfigureErrMsg
  client/client.go
Labels: fix

#464 fix: IgnoreAccessDeniedServiceDisabled should also ignore InsufficientPrivilegesException
  client/helpers.go
Labels: fix

#432 feat: Remove PII
  client/errors.go
  client/testing.go
  go.mod
  go.sum
  resources/provider/provider.go
  resources/services/redshift/mock_test.go
  resources/services/wafv2/rule_groups_mock_test.go
  resources/services/wafv2/web_acls_mock_test.go
Labels: feat

#468 fix: DaxClusters ListTags should use ARN
  resources/services/dax/clusters.go
Labels: fix

#469 chore: Add depndabot cq-provider-sdk
  .github/workflows/depndabot.yml
Labels: ignore-for-release

#465 docs: Remove 'labmda' from section about IAM auth
  docs/index.md
Labels: docs

#466 test: Merge integration tests with unittests
  .github/workflows/test_migration.yml
  go.mod
  go.sum
  resources/provider/provider_test.go
Labels: test

#448 feat: Added generic api error ignore routine
  client/helpers.go
  resources/services/efs/filesystems.go
  resources/services/eks/clusters.go
  resources/services/elbv1/load_balancers.go
  resources/services/iam/group_policies.go
  resources/services/iam/password_policies.go
  resources/services/iam/role_policies.go
  resources/services/iam/roles.go
  resources/services/iam/user_policies.go
  resources/services/lambda/functions.go
  resources/services/lambda/layers.go
  resources/services/s3/buckets.go
Labels: feat

#470 feat: AWS Org Support
  client/client.go
  client/config.go
  client/mocks/mock_organizations.go
  client/organizations.go
  client/organizations_test.go
  client/services.go
  docs/index.md
  go.sum
  resources/services/organizations/accounts.go
Labels: feat

#473 fix: Dyanamodb table not found error ignored
  resources/services/dynamodb/tables.go
Labels: fix

#474 docs: Copy authentication section from 'Getting Started' guide
  docs/index.md
Labels: docs

#476 fix: Empty admin account edge case
  client/organizations.go
  go.mod
  go.sum
Labels: fix

#477 feat: Update SDK for diag handling
  client/errors.go
  go.mod
  go.sum
Labels: feat

#479 chore: Removed duplicated dependabot
  .github/workflows/depndabot.yml
Labels: ignore-for-release

#480 chore: Synced file(s) with cloudquery/.github
  .github/dependabot.yml
Labels: ignore-for-release

#478 feat: Modules v2 support
  go.mod
  go.sum
  resources/provider/moduledata/drift/1/drift.hcl
  resources/provider/provider.go
Labels: feat

#485 fix: Diagnostic types in ErrorClassifier
  client/errors.go
Labels: fix

#484 chore: Delete pull-request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ignore-for-release

#482 feat: Add 'OwnershipControls' Column to S3 resource
  client/mocks/mock_s3.go
  client/services.go
  docs/tables/aws_s3_buckets.md
  resources/provider/migrations/postgres/17_v0.10.6.down.sql
  resources/provider/migrations/postgres/17_v0.10.6.up.sql
  resources/provider/migrations/timescale/17_v0.10.6.down.sql
  resources/provider/migrations/timescale/17_v0.10.6.up.sql
  resources/services/s3/buckets.go
  resources/services/s3/buckets_mock_test.go
Labels: feat

#486 chore: Synced file(s) with cloudquery/.github
  .github/dependabot.yml
Labels: ignore-for-release

#488 fix: MQ broker panic
  resources/services/mq/brokers.go
Labels: fix

#487 docs: Re-Add bullet about aws-sso.
  docs/index.md
Labels: docs

#491 fix: TGW Primary Key Issues
  resources/services/ec2/transit_gateways.go
Labels: fix

#503 fix: Deadlock on small instances
  go.mod
  go.sum
Labels: fix

#493 fix: Route 53 Traffic Policy Version PK
  resources/provider/migrations/postgres/18_v0.10.7.down.sql
  resources/provider/migrations/postgres/18_v0.10.7.up.sql
  resources/provider/migrations/timescale/18_v0.10.7.down.sql
  resources/provider/migrations/timescale/18_v0.10.7.up.sql
  resources/services/route53/traffic_policies.go
Labels: fix

#501 docs: Try to make it clearer that you can use multiple "accounts" blocks
  client/config.go
  docs/index.md
Labels: docs

#504 fix: Update endpoints
  client/data/partition_service_region.json
Labels: fix

#505 chore: Fix is-organization-member in integration tests
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#506 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#507 fix: TSDB migration for aws_route53_traffic_policy_versions
  resources/provider/migrations/timescale/18_v0.10.7.up.sql
  resources/provider/migrations/timescale/19_v0.10.8.down.sql
  resources/provider/migrations/timescale/19_v0.10.8.up.sql
Labels: fix
