Repository cloudquery/cq-provider-aws, pull requests merged in 2022-03, with the labels that each got.

#514 fix: Fetch each mq_broker_configuration only once, fetch current configuration
  resources/services/mq/brokers.go
  resources/services/mq/brokers_mock_test.go
Labels: fix

#513 fix: DirectConnect Gateways are global
  docs/tables/aws_directconnect_gateways.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/20_v0.10.9.down.sql
  resources/provider/migrations/postgres/20_v0.10.9.up.sql
  resources/provider/migrations/timescale/20_v0.10.9.down.sql
  resources/provider/migrations/timescale/20_v0.10.9.up.sql
  resources/services/directconnect/gateways.go
Labels: fix

#522 chore: Update SDK
  client/errors.go
  go.mod
  go.sum
Labels: ignore-for-release

#523 fix: Fix ResolveARNWithRegion
  client/helpers.go
Labels: fix

#524 chore: Add terraform plan action
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#511 chore: Update terraform
  terraform/.terraform.lock.hcl
  terraform/apigatewayv2.tf
  terraform/ec2_instance.tf
  terraform/ecs.tf
  terraform/lambda.tf
  terraform/mq.tf
  terraform/rds.tf
  terraform/redshift.tf
  terraform/s3.tf
  terraform/terraform.tf
  terraform/vpc.tf
Labels: ignore-for-release

#525 chore: Just test terraform workflow
  .github/workflows/terraform_plan.yml
  terraform/apigatewayv2.tf
  terraform/ec2_instance.tf
  terraform/ecs.tf
  terraform/iot.tf
  terraform/lambda.tf
  terraform/provider.tf
  terraform/s3.tf
  terraform/sagemaker.tf
  terraform/vpc.tf
Labels: ignore-for-release

#526 chore: Test new plan action
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
  terraform/mq.tf
Labels: ignore-for-release

#527 chore: Add Infracost
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#529 chore: Synced file(s) with cloudquery/.github
  .github/workflows/lint_doc.yml
  .github/workflows/test_integration.yml
  .github/workflows/test_unit.yml
Labels: ignore-for-release

#530 fix: Duplicated Query in docs
  docs/index.md
Labels: fix

#531 chore: Synced file(s) with cloudquery/.github
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#532 chore: Use OIDC for github actions
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#538 chore: Synced file(s) with cloudquery/.github
  .github/workflows/terraform_apply.yml
Labels: ignore-for-release

#539 chore: Synced file(s) with cloudquery/.github
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#535 fix: Add Pagination for ListResourceRecordSets
  resources/services/route53/hosted_zones.go
Labels: fix

#536 fix: Drift: aws_apigateway_usage_plan_keys resource should match the parent resource (usage_plan_id) as well as id
  resources/provider/moduledata/drift/1/drift.hcl
Labels: fix

#541 fix: Drift: aws_cloudfront_distribution_origins should match aws_cloudfront_distribution.origin
  resources/provider/moduledata/drift/1/drift.hcl
Labels: fix

#537 fix: Drift: Use correct identifier to match rds.instances, ignore non-tfstate attributes in deep mode
  resources/provider/moduledata/drift/1/drift.hcl
Labels: fix

#542 fix: Drift: Subresources should always match including the parent ID
  resources/provider/moduledata/drift/1/drift.hcl
Labels: fix

#543 fix: Classify ratelimit errors as throttling, redaction fixes
  client/errors.go
Labels: fix

#545 fix: ELB Nil Pointer Error
  resources/services/elbv2/listeners.go
Labels: fix

#548 fix: Drift: Match ec2.images with id/region
  resources/provider/moduledata/drift/1/drift.hcl
Labels: fix

#546 fix: Update EC2 EIPs Primary key
  resources/provider/migrations/postgres/21_v0.10.12.down.sql
  resources/provider/migrations/postgres/21_v0.10.12.up.sql
  resources/provider/migrations/timescale/21_v0.10.12.down.sql
  resources/provider/migrations/timescale/21_v0.10.12.up.sql
  resources/services/ec2/eips.go
Labels: fix

#551 chore: Synced file(s) with cloudquery/.github
  .github/workflows/README
  .github/workflows/endpoints.yml
  CODEOWNERS
Labels: ignore-for-release

#554 chore: Update SDK
  go.mod
  go.sum
Labels: ignore-for-release

#557 chore: Sync form .github
  .github/workflows/lint_doc.yml
  .github/workflows/lint_golang.yml
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
  .github/workflows/test_unit.yml
  scripts/terraform-apply-all.sh
  scripts/terraform-apply-changes-only.sh
  scripts/terraform-fmt-change-only.sh
  scripts/terraform-init-change-only.sh
  scripts/terraform-plan-change-only.sh
  scripts/terraform-validate-all.sh
  scripts/terraform-validate-change-only.sh
Labels: ignore-for-release

#559 chore: Sync form .github
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#560 chore: Sync form .github
  scripts/terraform-apply-all.sh
  scripts/terraform-apply-changes-only.sh
  scripts/terraform-fmt-change-only.sh
  scripts/terraform-init-change-only.sh
  scripts/terraform-plan-change-only.sh
  scripts/terraform-validate-all.sh
  scripts/terraform-validate-change-only.sh
Labels: ignore-for-release

#562 chore: Sync form .github
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#561 chore: Test shiny tf workflows
  terraform/iot/modules/test/iot.tf
Labels: ignore-for-release

#563 fix: Route53 hosted zones ListResourceRecordSets pagination
  resources/services/route53/hosted_zones.go
Labels: fix

#547 feat: Add CloudFormation stacks
  client/client.go
  client/mocks/mock_cloudformation.go
  client/services.go
  docs/tables/aws_cloudformation_stack_outputs.md
  docs/tables/aws_cloudformation_stack_resources.md
  docs/tables/aws_cloudformation_stacks.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/21_v0.10.12.down.sql
  resources/provider/migrations/postgres/21_v0.10.12.up.sql
  resources/provider/migrations/timescale/21_v0.10.12.down.sql
  resources/provider/migrations/timescale/21_v0.10.12.up.sql
  resources/provider/moduledata/drift/1/drift.hcl
  resources/provider/provider.go
  resources/services/apigatewayv2/api_gateway.hcl
  resources/services/cloudformation/gen.hcl
  resources/services/cloudformation/stacks.go
  resources/services/cloudformation/stacks_mock_test.go
  terraform/cloudformation/local/main.tf
  terraform/cloudformation/modules/test/provider.tf
  terraform/cloudformation/modules/test/stacks.tf
  terraform/cloudformation/modules/test/terraform.tf
  terraform/cloudformation/modules/test/variables.tf
  terraform/cloudformation/prod/main.tf
  terraform/cloudformation/prod/terraform.tf
  terraform/ec2/modules/test/instances.tf
  tools/tool.go
Labels: feat

#565 fix: Drift: CF stacks
  client/client.go
  resources/provider/moduledata/drift/1/drift.hcl
Labels: fix

#570 feat: Update SDK
  go.mod
  go.sum
Labels: feat

#574 chore: Debug is-organization-member (verbose)
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#575 chore: Add more verbose debugging to is_org action
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#566 feat: Add EC2 Instance Statuses
  client/mocks/mock_ec2.go
  client/services.go
  docs/tables/aws_ec2_instance_status_events.md
  docs/tables/aws_ec2_instance_statuses.md
  resources/provider/migrations/postgres/22_v0.10.13.down.sql
  resources/provider/migrations/postgres/22_v0.10.13.up.sql
  resources/provider/migrations/timescale/22_v0.10.13.down.sql
  resources/provider/migrations/timescale/22_v0.10.13.up.sql
  resources/provider/provider.go
  resources/services/ec2/instance_statuses.go
  resources/services/ec2/instance_statuses_mock_test.go
Labels: feat

#572 fix: Drop allocation_id from PK of aws_ec2_nat_gateway_addresses
  resources/provider/migrations/postgres/22_v0.10.14.down.sql
  resources/provider/migrations/postgres/22_v0.10.14.up.sql
  resources/provider/migrations/timescale/22_v0.10.14.down.sql
  resources/provider/migrations/timescale/22_v0.10.14.up.sql
  resources/services/ec2/nat_gateways.go
Labels: fix

#581 fix: Drift: nat_gateways and addresses
  resources/provider/moduledata/drift/1/drift.hcl
Labels: fix

#582 fix: Update endpoints
  client/data/partition_service_region.json
Labels: fix

#580 chore: Update migration files
  go.mod
  go.sum
  resources/provider/migrations/postgres/22_v0.10.13.down.sql
  resources/provider/migrations/postgres/22_v0.10.13.up.sql
  resources/provider/migrations/postgres/22_v0.10.14.down.sql
  resources/provider/migrations/postgres/22_v0.10.14.up.sql
  resources/provider/migrations/timescale/22_v0.10.13.down.sql
  resources/provider/migrations/timescale/22_v0.10.13.up.sql
  resources/provider/migrations/timescale/22_v0.10.14.down.sql
  resources/provider/migrations/timescale/22_v0.10.14.up.sql
Labels: ignore-for-release

#579 chore: Remove verbose debugging from is-org
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#590 chore: Sync form .github
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#588 fix: Remove unnecessary warn messages
  client/helpers.go
  resources/services/s3/buckets.go
Labels: fix

#591 fix: Handle GetModelTemplate application level errors
  .github/workflows/terraform_plan.yml
  client/helpers.go
  resources/provider/provider.go
  resources/services/apigateway/rest_apis.go
  resources/services/apigatewayv2/apis.go
  resources/services/cloudformation/stacks.go
  resources/services/cognito/user_pools.go
  resources/services/ec2/ebs_volumes.go
  resources/services/ec2/instance_statuses.go
  resources/services/ec2/instances.go
  resources/services/emr/clusters.go
  resources/services/lambda/functions.go
  resources/services/lambda/layers.go
  resources/services/rds/event_subscriptions.go
  resources/services/route53/hosted_zones.go
  resources/services/s3/buckets.go
  resources/services/sqs/queues.go
  terraform/accessanalyzer/prod/.terraform.lock.hcl
  terraform/apigateway2/modules/test/vpc.tf
  terraform/apigateway2/prod/.terraform.lock.hcl
  terraform/cloudformation/prod/.terraform.lock.hcl
  terraform/ec2/modules/test/instances.tf
  terraform/ec2/prod/.terraform.lock.hcl
  terraform/ecs/prod/.terraform.lock.hcl
  terraform/iot/prod/.terraform.lock.hcl
  terraform/lambda/prod/.terraform.lock.hcl
  terraform/mq/modules/test/brokers.tf
  terraform/rds/prod/.terraform.lock.hcl
Labels: fix

#592 chore: Sync form .github
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#593 chore: Remove Code of Conduct in favour of org wide
  CODE_OF_CONDUCT.md
Labels: ignore-for-release

#594 chore: Sync form .github
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#597 fix: Check regions
  client/client.go
  client/client_test.go
  client/helpers.go
  go.sum
Labels: fix

#499 feat: Decouple Admin Credentials From Member Account Assumption
  client/config.go
  client/organizations.go
  docs/index.md
Labels: feat

#598 chore: Sync form .github
  CONTRIBUTING.md
  docs/contributing/issue_reporting.md
Labels: ignore-for-release

#600 docs: Fix formatting
  docs/index.md
Labels: docs

#601 chore: Sync form .github
  Makefile
Labels: ignore-for-release

#602 chore: Sync form .github
  docs/contributing/issue_reporting.md
Labels: ignore-for-release

#606 feat: Upgrade SDK v0.8.13
  go.mod
  go.sum
Labels: feat

#609 fix: Drift: Match lambda functions by arn
  resources/provider/moduledata/drift/1/drift.hcl
Labels: fix

#611 chore: Sync form .github
  .github/workflows/issue_to_project.yml
  Makefile
Labels: ignore-for-release

#610 chore: Update endpoints
  client/data/partition_service_region.json
Labels: ignore-for-release

#630 feat: Always include failed account ID and region info along with failed resource ID
  client/errors.go
Labels: feat

#631 chore: Update SDK
  go.mod
  go.sum
Labels: ignore-for-release

#608 feat: Add last_launched_time to images
  client/mocks/mock_ec2.go
  client/services.go
  docs/tables/aws_ec2_images.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/24_v0.10.16.down.sql
  resources/provider/migrations/postgres/24_v0.10.16.up.sql
  resources/provider/migrations/timescale/24_v0.10.16.down.sql
  resources/provider/migrations/timescale/24_v0.10.16.up.sql
  resources/services/ec2/images.go
  resources/services/ec2/images_mock_test.go
Labels: feat

#632 chore: Update endpoints
  client/data/partition_service_region.json
Labels: ignore-for-release

#635 fix: Drop unnecessary EndpointResolver
  resources/services/ec2/images.go
Labels: fix

#639 feat: Added workspaces tf module
  terraform/lambda/modules/test/functions.tf
  terraform/lambda/modules/test/layers.tf
  terraform/lambda/prod/.terraform.lock.hcl
  terraform/workspaces/local/main.tf
  terraform/workspaces/local/variables.tf
  terraform/workspaces/modules/test/directory.tf
  terraform/workspaces/modules/test/provider.tf
  terraform/workspaces/modules/test/terraform.tf
  terraform/workspaces/modules/test/variables.tf
  terraform/workspaces/modules/test/workspace.tf
  terraform/workspaces/prod/.terraform.lock.hcl
  terraform/workspaces/prod/main.tf
  terraform/workspaces/prod/terraform.tf
Labels: feat

#641 fix: Endpoint Updates and doc Fixes
  Makefile
  client/data/partition_service_region.json
  docs/index.md
Labels: fix

#643 feat: Add redshift event subscription tf
  terraform/redshift/modules/test/redshift.tf
Labels: feat

#634 feat: Added AWS workspaces
  client/client.go
  client/helpers.go
  client/mocks/mock_workspaces.go
  client/services.go
  docs/tables/aws_workspaces_directories.md
  docs/tables/aws_workspaces_workspaces.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/24_v0.10.16.down.sql
  resources/provider/migrations/postgres/24_v0.10.16.up.sql
  resources/provider/migrations/timescale/24_v0.10.16.down.sql
  resources/provider/migrations/timescale/24_v0.10.16.up.sql
  resources/provider/provider.go
  resources/services/workspaces/directories.go
  resources/services/workspaces/directories_mock_test.go
  resources/services/workspaces/gen.hcl
  resources/services/workspaces/workspaces.go
  resources/services/workspaces/workspaces_mock_test.go
Labels: feat
