Repository cloudquery/cq-provider-aws, pull requests merged in 2022-05, with the labels that each got.

#810 feat: Add tags to sns fetching
  .gitignore
  client/mocks/mock_sns.go
  client/services.go
  docs/tables/aws_sns_topics.md
  resources/provider/migrations/postgres/28_v0.11.2.down.sql
  resources/provider/migrations/postgres/28_v0.11.2.up.sql
  resources/provider/migrations/timescale/28_v0.11.2.down.sql
  resources/provider/migrations/timescale/28_v0.11.2.up.sql
  resources/services/sns/topics.go
  resources/services/sns/topics_mock_test.go
  terraform/sns/modules/test/sns.tf
Labels: feat

#751 feat: Add AWS::ElasticBeanstalk::ApplicationVersion
  client/helpers.go
  client/mocks/mock_elasticbeanstalk.go
  client/services.go
  docs/tables/aws_elasticbeanstalk_application_versions.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/28_v0.11.2.down.sql
  resources/provider/migrations/postgres/28_v0.11.2.up.sql
  resources/provider/migrations/timescale/28_v0.11.2.down.sql
  resources/provider/migrations/timescale/28_v0.11.2.up.sql
  resources/provider/provider.go
  resources/services/elasticbeanstalk/application_versions.go
  resources/services/elasticbeanstalk/application_versions_mock_test.go
  resources/services/elasticbeanstalk/environments.go
  resources/services/elasticbeanstalk/gen.hcl
Labels: feat

#807 feat: Add retry log
  client/client.go
  client/retry.go
Labels: feat

#801 fix: Debug SDK
  client/client.go
  go.mod
  go.sum
Labels: fix

#821 fix: Normalize InvalidSnapshot.NotFound error
  client/errors.go
  client/errors_test.go
Labels: fix

#818 fix: Backup Global Settings: Ignore not member of an org error
  resources/services/backup/global_settings.go
Labels: fix

#815 fix: Fetch backup tags only for the resources that support it
  client/helpers.go
  resources/services/backup/vaults.go
  resources/services/backup/vaults_mock_test.go
Labels: fix

#845 fix: Hotfix for athena e2e infrastructure
  terraform/athena/modules/test/database.tf
Labels: fix

#797 fix: Adjust redshift PKs
  docs/tables/aws_redshift_event_subscriptions.md
  docs/tables/aws_redshift_snapshots.md
  resources/provider/migrations/postgres/29_v0.11.3.down.sql
  resources/provider/migrations/postgres/29_v0.11.3.up.sql
  resources/provider/migrations/timescale/29_v0.11.3.down.sql
  resources/provider/migrations/timescale/29_v0.11.3.up.sql
  resources/services/redshift/clusters.go
  resources/services/redshift/clusters_mock_test.go
  resources/services/redshift/event_subscriptions.go
  resources/services/redshift/snapshots.go
  resources/services/redshift/subnet_groups.go
Labels: fix

#837 fix: Ignore cloudformation validation error on not existing stacks
  client/helpers.go
  client/helpers_test.go
  resources/services/cloudformation/stacks.go
Labels: fix

#834 chore(deps): Delete `dependabot.yml`
  .github/dependabot.yml
Labels: ignore-for-release

#844 fix: Ignore role tags fetching when role does not exists
  resources/services/iam/roles.go
Labels: fix

#850 chore: Truncate redshift table during migrations
  resources/provider/migrations/postgres/29_v0.11.3.down.sql
  resources/provider/migrations/postgres/29_v0.11.3.up.sql
  resources/provider/migrations/timescale/29_v0.11.3.down.sql
  resources/provider/migrations/timescale/29_v0.11.3.up.sql
Labels: ignore-for-release

#852 fix: Fix possible nil pointer dereferences
  client/helpers_test.go
  resources/services/ecs/clusters.go
Labels: fix

#848 fix: WAFV2 Managed Rules PK
  Makefile
  client/filters.go
  docs/tables/aws_wafv2_managed_rule_groups.md
  docs/tables/aws_wafv2_rule_groups.md
  docs/tables/aws_wafv2_web_acls.md
  resources/provider/migrations/postgres/29_v0.11.3.down.sql
  resources/provider/migrations/postgres/29_v0.11.3.up.sql
  resources/provider/migrations/timescale/29_v0.11.3.down.sql
  resources/provider/migrations/timescale/29_v0.11.3.up.sql
  resources/services/wafv2/ipsets.go
  resources/services/wafv2/managed_rule_groups.go
  resources/services/wafv2/regex_pattern_sets.go
  resources/services/wafv2/rule_groups.go
  resources/services/wafv2/web_acls.go
Labels: fix

#829 fix: Fix panic on fetching wafv2 without us-east-1
  client/client.go
  client/multiplexers.go
Labels: fix

#855 fix: Reduce retry params
  client/config.go
  docs/index.md
Labels: fix

#862 fix: Classify UnrecognizedClientException as Access error
  client/errors.go
  client/helpers.go
Labels: fix

#842 feat: Support AWS partitions
  client/helpers.go
  client/helpers_test.go
Labels: feat

#881 fix: Lambda function alias duplicate PK
  resources/services/lambda/functions.go
Labels: bug

#840 feat: Add S3 Bucket fetch speed improvement
  resources/services/s3/buckets.go
Labels: feat

#814 feat: Add waf/wafv2 logging config
  docs/tables/aws_waf_web_acl_logging_configuration.md
  docs/tables/aws_wafv2_web_acl_logging_configuration.md
  resources/services/waf/rules.go
  resources/services/waf/subscribed_rule_groups.go
  resources/services/waf/web_acls.go
  resources/services/wafv2/rule_groups.go
  resources/services/wafv2/web_acls.go
Labels: feat
