Repository cloudquery/cq-provider-aws, pull requests merged in 2022-01, with the labels that each got.

#415 fix: Sagemaker training jobs panic resolved
  resources/services/sagemaker/training_jobs.go
Labels: fix

#413 fix: Ignore organization tail tags if permissions are missing
  resources/services/cloudtrail/trails.go
  resources/services/cloudtrail/trails_mock_test.go
Labels: fix

#417 chore: Synced file(s) with cloudquery/.github
  .github/workflows/add_tags.yml
Labels: ignore-for-release

#396 feat: AWS Provider Improvements And Docs
  .github/workflows/cq_fetch.yml
  .github/workflows/int_test.yml
  client/client.go
  client/client_test.go
  client/config.go
  docs/index.md
Labels: feat

#418 fix: Continue remove account_id in config
  client/config.go
  client/data/partition_service_region.json
  client/testdata/assume_role.hcl
Labels: fix

#420 fix: E2E tests
  client/client.go
  client/client_test.go
Labels: fix

#424 fix: Make lambda runtimes global table
  package.json
  resources/services/lambda/runtimes.go
Labels: fix

#422 feat: Efs filesystem backup status added
  client/mocks/mock_efs.go
  client/services.go
  docs/tables/aws_acm_certificates.md
  docs/tables/aws_applicationautoscaling_policies.md
  docs/tables/aws_cognito_user_pools.md
  docs/tables/aws_dynamodb_table_continuous_backups.md
  docs/tables/aws_ecs_cluster_services.md
  docs/tables/aws_efs_filesystems.md
  docs/tables/aws_elasticbeanstalk_applications.md
  docs/tables/aws_elasticsearch_domains.md
  docs/tables/aws_elbv2_listener_default_actions.md
  docs/tables/aws_emr_clusters.md
  docs/tables/aws_sagemaker_endpoint_configuration_production_variants.md
  docs/tables/aws_sagemaker_model_containers.md
  docs/tables/aws_sagemaker_notebook_instances.md
  docs/tables/aws_sagemaker_training_job_debug_hook_config.md
  docs/tables/aws_sagemaker_training_job_debug_rule_configurations.md
  docs/tables/aws_sagemaker_training_job_input_data_config.md
  docs/tables/aws_sagemaker_training_job_profiler_rule_configurations.md
  resources/provider/migrations/postgres/15_v0.10.0.down.sql
  resources/provider/migrations/postgres/15_v0.10.0.up.sql
  resources/provider/migrations/timescale/15_v0.10.0.up.sql
  resources/services/acm/certificates.go
  resources/services/applicationautoscaling/policies.go
  resources/services/cognito/user_pools.go
  resources/services/dynamodb/tables.go
  resources/services/ecs/clusters.go
  resources/services/efs/filesystems.go
  resources/services/efs/filesystems_mock_test.go
  resources/services/elasticbeanstalk/applications.go
  resources/services/elasticsearch/domains.go
  resources/services/elbv2/listeners.go
  resources/services/emr/clusters.go
  resources/services/sagemaker/endpoint_configurations.go
  resources/services/sagemaker/models.go
  resources/services/sagemaker/notebook_instances.go
  resources/services/sagemaker/training_jobs.go
Labels: feat

#425 fix: Hotfix for efs filesystems
  docs/tables/aws_efs_filesystems.md
  resources/services/efs/filesystems.go
Labels: fix

#426 fix: Efs filesystem backups hotifx
  resources/services/efs/filesystems.go
Labels: fix

#427 fix: Sagemaker panics
  resources/services/sagemaker/training_jobs.go
Labels: fix

#428 feat: Upgrade SDK v0.7.0
  go.mod
  go.sum
Labels: feat

#429 fix: Config packs bad region unknown error
  resources/services/cloudtrail/trails_mock_test.go
  resources/services/config/conformance_pack.go
Labels: fix

#430 fix: Panic in lambda functions
  resources/services/lambda/functions.go
Labels: fix

#431 fix: RDS Certificates PK issue and column names
  resources/provider/migrations/postgres/15_v0.10.0.down.sql
  resources/provider/migrations/postgres/15_v0.10.0.up.sql
  resources/provider/migrations/timescale/15_v0.10.0.down.sql
  resources/provider/migrations/timescale/15_v0.10.0.up.sql
  resources/services/rds/certificates.go
Labels: fix

#438 feat: Add role session name
  client/client.go
  client/config.go
  docs/index.md
Labels: feat

#435 chore: Remove release_binary.yml
  .github/workflows/release_binary.yml
Labels: ignore-for-release

#441 fix: Fix init config
  client/config.go
Labels: fix

#439 chore: Remove duplicate mock test workflow
  .github/workflows/test.yml
Labels: ignore-for-release

#443 fix: Added nil check to avoid panics in elvb2 linters and lambda functions
  resources/services/elbv2/listeners.go
  resources/services/lambda/functions.go
Labels: fix

#440 fix: Added skip error if there is no policies attached to role
  resources/services/iam/roles.go
Labels: fix

#437 chore: Synced file(s) with cloudquery/.github
  .github/workflows/test_migration.yml
Labels: ignore-for-release

#434 chore: Run integration tests on approved forks
  .github/workflows/int_test.yml
Labels: ignore-for-release

#452 chore: Fix test_integration.yml
  .github/workflows/lint_doc.yml
  .github/workflows/lint_golang.yml
  .github/workflows/test_integration.yml
  .github/workflows/test_unit.yml
Labels: ignore-for-release

#453 feat: Update AWS regions
  .github/workflows/test_unit.yml
  client/data/partition_service_region.json
Labels: feat

#454 chore: Fix test_integration.yml
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#458 chore: Fix is_organization_member job
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#460 chore: Final fix to test_integration.yml
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#451 fix: Fixed pk constraint in aws_rds_certificates
  resources/provider/migrations/postgres/16_v0.10.2.down.sql
  resources/provider/migrations/postgres/16_v0.10.2.up.sql
  resources/provider/migrations/timescale/16_v0.10.2.down.sql
  resources/provider/migrations/timescale/16_v0.10.2.up.sql
  resources/services/rds/certificates.go
Labels: fix

#462 fix: Ignore WAFNonexistentItemException (WAFV2.GetWebACLForResource) on elbv2.load_balancers web_acl_arn
  resources/services/elbv2/load_balancers.go
Labels: fix
