Repository cloudquery/cq-provider-aws, pull requests merged in 2022-04, with the labels that each got.

#642 feat: Implement Redshift event subscriptions
  client/mocks/mock_redshift.go
  client/services.go
  docs/tables/aws_redshift_event_subscriptions.md
  resources/provider/migrations/postgres/25_v0.10.17.down.sql
  resources/provider/migrations/postgres/25_v0.10.17.up.sql
  resources/provider/migrations/timescale/25_v0.10.17.down.sql
  resources/provider/migrations/timescale/25_v0.10.17.up.sql
  resources/provider/provider.go
  resources/services/redshift/clusters.go
  resources/services/redshift/event_subscriptions.go
  resources/services/redshift/event_subscriptions_mock_test.go
Labels: feat

#645 feat: Implement Redshift snapshots
  client/mocks/mock_redshift.go
  client/services.go
  docs/tables/aws_redshift_snapshot_accounts_with_restore_access.md
  docs/tables/aws_redshift_snapshots.md
  resources/provider/migrations/postgres/25_v0.10.17.down.sql
  resources/provider/migrations/postgres/25_v0.10.17.up.sql
  resources/provider/migrations/timescale/25_v0.10.17.down.sql
  resources/provider/migrations/timescale/25_v0.10.17.up.sql
  resources/services/redshift/clusters.go
  resources/services/redshift/mock_test.go
  resources/services/redshift/snapshots.go
Labels: feat

#644 fix: Doc Formatting
  docs/index.md
Labels: fix

#648 feat: Add backup TF files
  terraform/backup/local/main.tf
  terraform/backup/modules/test/backup.tf
  terraform/backup/modules/test/provider.tf
  terraform/backup/modules/test/terraform.tf
  terraform/backup/modules/test/variables.tf
  terraform/backup/prod/.terraform.lock.hcl
  terraform/backup/prod/main.tf
  terraform/backup/prod/terraform.tf
Labels: feat

#651 chore: Update Regions
  client/data/partition_service_region.json
Labels: ignore-for-release

#654 fix: Update SNS subscription PK
  resources/provider/migrations/postgres/24_v0.10.16.down.sql
  resources/provider/migrations/postgres/24_v0.10.16.up.sql
  resources/provider/migrations/timescale/24_v0.10.16.down.sql
  resources/provider/migrations/timescale/24_v0.10.16.up.sql
  resources/services/sns/subscriptions.go
Labels: fix

#653 feat: Added Codepipeline terraform module
  terraform/codepipeline/local/main.tf
  terraform/codepipeline/modules/test/codepipeline.tf
  terraform/codepipeline/modules/test/provider.tf
  terraform/codepipeline/modules/test/terraform.tf
  terraform/codepipeline/modules/test/variables.tf
  terraform/codepipeline/prod/.terraform.lock.hcl
  terraform/codepipeline/prod/main.tf
  terraform/codepipeline/prod/terraform.tf
Labels: feat

#587 feat: Added mq configurations revisions
  client/mocks/mock_mq.go
  client/services.go
  docs/tables/aws_mq_broker_configuration_revisions.md
  docs/tables/aws_mq_broker_configurations.md
  docs/tables/aws_mq_brokers.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/24_v0.10.16.down.sql
  resources/provider/migrations/postgres/24_v0.10.16.up.sql
  resources/provider/migrations/timescale/24_v0.10.16.down.sql
  resources/provider/migrations/timescale/24_v0.10.16.up.sql
  resources/provider/provider.go
  resources/services/mq/brokers.go
  resources/services/mq/brokers_mock_test.go
Labels: feat

#660 chore: Update backup tf files
  terraform/backup/modules/test/backup.tf
Labels: ignore-for-release

#657 feat: AWS codepipeline
  client/client.go
  client/mocks/mock_codepipeline.go
  client/services.go
  docs/tables/aws_codepipeline_pipeline_stage_actions.md
  docs/tables/aws_codepipeline_pipeline_stages.md
  docs/tables/aws_codepipeline_pipelines.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/24_v0.10.16.down.sql
  resources/provider/migrations/postgres/24_v0.10.16.up.sql
  resources/provider/migrations/timescale/24_v0.10.16.down.sql
  resources/provider/migrations/timescale/24_v0.10.16.up.sql
  resources/provider/provider.go
  resources/services/codepipeline/gen.hcl
  resources/services/codepipeline/pipelines.go
  resources/services/codepipeline/pipelines_mock_test.go
Labels: feat

#667 feat: Add iam users descriptions
  docs/tables/aws_iam_user_access_keys.md
  docs/tables/aws_iam_user_attached_policies.md
  docs/tables/aws_iam_user_groups.md
  docs/tables/aws_iam_users.md
  resources/services/iam/users.go
Labels: feat

#671 fix: PKs for Virtual MFA Device
  resources/provider/migrations/postgres/24_v0.10.16.down.sql
  resources/provider/migrations/postgres/24_v0.10.16.up.sql
  resources/provider/migrations/timescale/24_v0.10.16.down.sql
  resources/provider/migrations/timescale/24_v0.10.16.up.sql
  resources/services/cloudformation/stacks.go
  resources/services/iam/virtual_mfa_devices.go
Labels: fix

#646 feat: Ecs tasks
  client/mocks/mock_ecs.go
  client/services.go
  docs/tables/aws_ecs_cluster_container_instance_attributes.md
  docs/tables/aws_ecs_cluster_container_instance_health_status_details.md
  docs/tables/aws_ecs_cluster_container_instance_registered_resources.md
  docs/tables/aws_ecs_cluster_container_instance_remaining_resources.md
  docs/tables/aws_ecs_cluster_container_instances.md
  docs/tables/aws_ecs_cluster_service_deployments.md
  docs/tables/aws_ecs_cluster_service_events.md
  docs/tables/aws_ecs_cluster_service_service_registries.md
  docs/tables/aws_ecs_cluster_service_task_set_service_registries.md
  docs/tables/aws_ecs_cluster_service_task_sets.md
  docs/tables/aws_ecs_cluster_services.md
  docs/tables/aws_ecs_cluster_task_attachments.md
  docs/tables/aws_ecs_cluster_task_containers.md
  docs/tables/aws_ecs_cluster_tasks.md
  docs/tables/aws_ecs_clusters.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/24_v0.10.16.down.sql
  resources/provider/migrations/postgres/24_v0.10.16.up.sql
  resources/provider/migrations/timescale/24_v0.10.16.down.sql
  resources/provider/migrations/timescale/24_v0.10.16.up.sql
  resources/provider/provider.go
  resources/services/ecs/cluster_mock_test.go
  resources/services/ecs/clusters.go
Labels: feat

#677 chore: Added codepipeline::webhook tf
  terraform/codepipeline/local/main.tf
  terraform/codepipeline/local/variables.tf
  terraform/codepipeline/modules/test/webhook.tf
Labels: ignore-for-release

#679 chore: Add ledger tf files
  terraform/qldb/local/main.tf
  terraform/qldb/modules/test/ledger.tf
  terraform/qldb/modules/test/provider.tf
  terraform/qldb/modules/test/terraform.tf
  terraform/qldb/modules/test/variables.tf
  terraform/qldb/prod/main.tf
  terraform/qldb/prod/terraform.tf
Labels: ignore-for-release

#684 fix: Added tags for codepipeline resources
  terraform/codepipeline/modules/test/codepipeline.tf
  terraform/codepipeline/modules/test/webhook.tf
Labels: fix

#678 feat: Codepipeline webhooks
  client/data/partition_service_region.json
  client/mocks/mock_codepipeline.go
  client/services.go
  docs/tables/aws_codepipeline_webhook_filters.md
  docs/tables/aws_codepipeline_webhooks.md
  resources/provider/migrations/postgres/24_v0.10.16.down.sql
  resources/provider/migrations/postgres/24_v0.10.16.up.sql
  resources/provider/migrations/postgres/25_v0.10.17.down.sql
  resources/provider/migrations/postgres/25_v0.10.17.up.sql
  resources/provider/migrations/timescale/24_v0.10.16.down.sql
  resources/provider/migrations/timescale/24_v0.10.16.up.sql
  resources/provider/migrations/timescale/25_v0.10.17.down.sql
  resources/provider/migrations/timescale/25_v0.10.17.up.sql
  resources/provider/provider.go
  resources/services/codepipeline/gen.hcl
  resources/services/codepipeline/webhooks.go
  resources/services/codepipeline/webhooks_mock_test.go
Labels: feat

#687 chore: Update endpoints
  client/data/partition_service_region.json
Labels: ignore-for-release

#676 chore: Add TF for wafv2 ipsets and regex sets
  terraform/wafv2/local/main.tf
  terraform/wafv2/modules/test/ipsets.tf
  terraform/wafv2/modules/test/provider.tf
  terraform/wafv2/modules/test/regex_pattern_sets.tf
  terraform/wafv2/modules/test/terraform.tf
  terraform/wafv2/modules/test/variables.tf
  terraform/wafv2/prod/.terraform.lock.hcl
  terraform/wafv2/prod/main.tf
  terraform/wafv2/prod/terraform.tf
Labels: ignore-for-release

#686 chore: Add WAF Regional TF resources
  terraform/wafregional/local/.terraform.lock.hcl
  terraform/wafregional/local/main.tf
  terraform/wafregional/modules/test/provider.tf
  terraform/wafregional/modules/test/terraform.tf
  terraform/wafregional/modules/test/variables.tf
  terraform/wafregional/modules/test/wafregional.tf
  terraform/wafregional/prod/.terraform.lock.hcl
  terraform/wafregional/prod/main.tf
  terraform/wafregional/prod/terraform.tf
Labels: ignore-for-release

#688 chore: Added ec2 egress-only internet gateway tf
  terraform/ec2/modules/test/vpc.tf
Labels: ignore-for-release

#693 feat: Reduce ECS API Calls
  go.sum
  resources/services/ecs/task_definitions.go
  resources/services/ecs/task_definitions_mock_test.go
Labels: feat

#685 feat: Tag helper
  client/helpers.go
  client/helpers_test.go
  client/resolvers.go
  client/resolvers_test.go
  resources/services/acm/certificates.go
  resources/services/backup/vaults.go
  resources/services/cloudfront/distributions.go
  resources/services/cloudtrail/trails.go
  resources/services/codepipeline/pipelines.go
  resources/services/codepipeline/webhooks.go
  resources/services/dax/clusters.go
  resources/services/dynamodb/tables.go
  resources/services/ecs/clusters.go
  resources/services/elbv1/load_balancers.go
  resources/services/emr/clusters.go
  resources/services/iam/openid_connect_identity_providers.go
  resources/services/iam/saml_identity_providers.go
  resources/services/iot/iot_billing_groups.go
  resources/services/iot/iot_jobs.go
  resources/services/iot/iot_policies.go
  resources/services/iot/iot_security_profiles.go
  resources/services/iot/iot_thing_groups.go
  resources/services/iot/iot_thing_types.go
  resources/services/iot/iot_topic_rules.go
  resources/services/rds/cluster_parameter_groups.go
  resources/services/rds/db_parameter_groups.go
  resources/services/rds/db_security_groups.go
  resources/services/rds/event_subscriptions.go
  resources/services/redshift/event_subscriptions.go
  resources/services/redshift/snapshots.go
  resources/services/route53/domains.go
  resources/services/route53/health_checks.go
  resources/services/route53/hosted_zones.go
  resources/services/ssm/documents.go
Labels: feat

#699 chore: OldGo compatibility
  client/helpers.go
  client/resolvers.go
Labels: ignore-for-release

#689 feat: Added ec2 egress only igw
  client/mocks/mock_ec2.go
  client/services.go
  docs/tables/aws_ec2_egress_only_internet_gateways.md
  resources/provider/migrations/postgres/25_v0.10.17.down.sql
  resources/provider/migrations/postgres/25_v0.10.17.up.sql
  resources/provider/migrations/timescale/25_v0.10.17.down.sql
  resources/provider/migrations/timescale/25_v0.10.17.up.sql
  resources/provider/provider.go
  resources/services/ec2/egress_only_internet_gateways.go
  resources/services/ec2/egress_only_internet_gateways_mock_test.go
  resources/services/ec2/gen.hcl
Labels: feat

#680 feat: Add WebACL Cloudfront fetching
  client/client.go
  client/mocks/mock_cloudfront.go
  client/services.go
  resources/services/wafv2/web_acls.go
  resources/services/wafv2/web_acls_mock_test.go
Labels: feat

#702 feat: Qldb ledgers
  client/client.go
  client/mocks/mock_qldb.go
  client/services.go
  docs/tables/aws_qldb_ledger_journal_kinesis_streams.md
  docs/tables/aws_qldb_ledger_journal_s3_exports.md
  docs/tables/aws_qldb_ledgers.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/24_v0.10.16.down.sql
  resources/provider/migrations/postgres/24_v0.10.16.up.sql
  resources/provider/migrations/postgres/25_v0.10.17.down.sql
  resources/provider/migrations/postgres/25_v0.10.17.up.sql
  resources/provider/migrations/timescale/24_v0.10.16.down.sql
  resources/provider/migrations/timescale/25_v0.10.17.down.sql
  resources/provider/migrations/timescale/25_v0.10.17.up.sql
  resources/provider/provider.go
  resources/services/qldb/gen.hcl
  resources/services/qldb/ledgers.go
  resources/services/qldb/ledgers_mock_test.go
Labels: feat

#701 feat: Parallelize ECS Task Definition Fetch
  .gitignore
  resources/services/ecs/task_definitions.go
  terraform/ecs/modules/test/task_definitions.tf
Labels: feat

#703 chore: Add AutoScaling ScheduledActions TF Resources
  terraform/autoscaling/local/main.tf
  terraform/autoscaling/modules/test/autoscaling.tf
  terraform/autoscaling/modules/test/provider.tf
  terraform/autoscaling/modules/test/terraform.tf
  terraform/autoscaling/modules/test/variables.tf
  terraform/autoscaling/prod/.terraform.lock.hcl
  terraform/autoscaling/prod/main.tf
  terraform/autoscaling/prod/terraform.tf
Labels: ignore-for-release

#696 feat: Add AutoScaling ScheduledActions
  client/mocks/mock_autoscaling.go
  client/services.go
  docs/tables/aws_autoscaling_scheduled_actions.md
  resources/provider/migrations/postgres/26_v0.10.18.down.sql
  resources/provider/migrations/postgres/26_v0.10.18.up.sql
  resources/provider/migrations/timescale/26_v0.10.18.down.sql
  resources/provider/migrations/timescale/26_v0.10.18.up.sql
  resources/provider/provider.go
  resources/services/autoscaling/gen.hcl
  resources/services/autoscaling/scheduled_actions.go
  resources/services/autoscaling/scheduled_actions_mock_test.go
Labels: feat

#681 feat: Add WAF Regional resources
  client/client.go
  client/helpers.go
  client/mocks/wafregional.go
  client/services.go
  docs/tables/aws_wafregional_rate_based_rule_match_predicates.md
  docs/tables/aws_wafregional_rate_based_rules.md
  docs/tables/aws_wafregional_rule_groups.md
  docs/tables/aws_wafregional_rule_predicates.md
  docs/tables/aws_wafregional_rules.md
  docs/tables/aws_wafregional_web_acl_rules.md
  docs/tables/aws_wafregional_web_acls.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/27_v0.10.19.down.sql
  resources/provider/migrations/postgres/27_v0.10.19.up.sql
  resources/provider/migrations/timescale/27_v0.10.19.down.sql
  resources/provider/migrations/timescale/27_v0.10.19.up.sql
  resources/provider/provider.go
  resources/services/wafregional/rate_based_rules.go
  resources/services/wafregional/rate_based_rules.hcl
  resources/services/wafregional/rate_based_rules_mock_test.go
  resources/services/wafregional/rule_groups.go
  resources/services/wafregional/rule_groups.hcl
  resources/services/wafregional/rule_groups_mock_test.go
  resources/services/wafregional/rules.go
  resources/services/wafregional/rules.hcl
  resources/services/wafregional/rules_mock_test.go
  resources/services/wafregional/web_acls.go
  resources/services/wafregional/web_acls.hcl
  resources/services/wafregional/web_acls_mock_test.go
Labels: feat

#705 chore: Drift for new resources
  resources/provider/moduledata/drift/2/drift.hcl
Labels: ignore-for-release

#708 chore(docs): Fix typo and update wording
  docs/contributing/development_environment.md
Labels: ignore-for-release

#710 fix: Update AWS endpoints
  client/data/partition_service_region.json
Labels: fix

#713 chore: Add ec2 network interface
  terraform/ec2/modules/test/network-interface.tf
  terraform/lambda/modules/test/functions.tf
Labels: ignore-for-release

#714 chore: Add xray encryption config
  terraform/xray/local/main.tf
  terraform/xray/local/variables.tf
  terraform/xray/modules/test/encryption-config.tf
  terraform/xray/modules/test/provider.tf
  terraform/xray/modules/test/terraform.tf
  terraform/xray/modules/test/variables.tf
  terraform/xray/prod/.terraform.lock.hcl
  terraform/xray/prod/main.tf
  terraform/xray/prod/terraform.tf
Labels: ignore-for-release

#698 feat: Added xray encryption config
  client/client.go
  client/mocks/xray.go
  client/services.go
  docs/tables/aws_xray_encryption_config.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/25_v0.10.17.down.sql
  resources/provider/migrations/postgres/25_v0.10.17.up.sql
  resources/provider/migrations/timescale/25_v0.10.17.down.sql
  resources/provider/migrations/timescale/25_v0.10.17.up.sql
  resources/provider/provider.go
  resources/services/xray/encryption_config.go
  resources/services/xray/encryption_config_mock_test.go
  resources/services/xray/gen.hcl
Labels: feat

#717 chore: Add ec2 host (dedicated)
  terraform/ec2/modules/test/dedicated-host.tf
Labels: ignore-for-release

#697 feat: Added ec2 host (dedicated)
  client/mocks/mock_ec2.go
  client/services.go
  docs/tables/aws_ec2_host_available_instance_capacity.md
  docs/tables/aws_ec2_host_instances.md
  docs/tables/aws_ec2_hosts.md
  resources/provider/migrations/postgres/25_v0.10.17.down.sql
  resources/provider/migrations/postgres/25_v0.10.17.up.sql
  resources/provider/migrations/timescale/25_v0.10.17.down.sql
  resources/provider/migrations/timescale/25_v0.10.17.up.sql
  resources/provider/provider.go
  resources/services/ec2/gen.hcl
  resources/services/ec2/hosts.go
  resources/services/ec2/hosts_mock_test.go
Labels: feat

#718 chore: Fix migrations
  resources/provider/migrations/postgres/25_v0.10.17.down.sql
  resources/provider/migrations/postgres/25_v0.10.17.up.sql
  resources/provider/migrations/postgres/26_v0.10.18.down.sql
  resources/provider/migrations/postgres/26_v0.10.18.up.sql
  resources/provider/migrations/postgres/27_v0.10.19.down.sql
  resources/provider/migrations/postgres/27_v0.10.19.up.sql
  resources/provider/migrations/timescale/25_v0.10.17.down.sql
  resources/provider/migrations/timescale/25_v0.10.17.up.sql
  resources/provider/migrations/timescale/26_v0.10.18.down.sql
  resources/provider/migrations/timescale/26_v0.10.18.up.sql
  resources/provider/migrations/timescale/27_v0.10.19.down.sql
  resources/provider/migrations/timescale/27_v0.10.19.up.sql
Labels: ignore-for-release

#716 chore: More drift resources
  resources/provider/moduledata/drift/2/drift.hcl
Labels: ignore-for-release

#719 fix: Broken migrations
  resources/provider/migrations/postgres/24_v0.10.16.up.sql
  resources/provider/migrations/postgres/25_v0.10.17.down.sql
  resources/provider/migrations/timescale/24_v0.10.16.up.sql
  resources/provider/migrations/timescale/25_v0.10.17.down.sql
Labels: fix

#722 chore: Add backup settings tf
  terraform/backup/modules/test/settings.tf
Labels: ignore-for-release

#721 fix: Redact username in diags, more redactions
  client/errors.go
  client/errors_test.go
Labels: fix

#734 fix: Update AWS endpoints
  client/data/partition_service_region.json
Labels: fix

#732 chore: Remove dead code
  client/testing.go
Labels: ignore-for-release

#731 feat: Add new fields to ecs_task_definitions
  docs/tables/aws_ecs_task_definitions.md
  resources/provider/migrations/postgres/26_v0.10.18.down.sql
  resources/provider/migrations/postgres/26_v0.10.18.up.sql
  resources/provider/migrations/timescale/26_v0.10.18.down.sql
  resources/provider/migrations/timescale/26_v0.10.18.up.sql
  resources/services/ecs/task_definitions.go
Labels: feat

#712 chore: Add SSM association TF
  terraform/ssm/modules/test/ssm.tf
Labels: ignore-for-release

#737 chore: Remove stale issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: ignore-for-release

#746 fix: Classifier redaction from EBS
  client/errors.go
  client/errors_test.go
Labels: fix

#736 feat: Update kms keys to latest sdk
  docs/tables/aws_kms_keys.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/26_v0.10.18.down.sql
  resources/provider/migrations/postgres/26_v0.10.18.up.sql
  resources/provider/migrations/timescale/26_v0.10.18.down.sql
  resources/provider/migrations/timescale/26_v0.10.18.up.sql
  resources/provider/provider.go
  resources/services/kms/keys.go
  resources/services/kms/keys.hcl
  resources/services/kms/keys_mock_test.go
Labels: feat

#747 feat: Add ConformancePackRuleCompliances
  client/mocks/mock_configservice.go
  client/services.go
  docs/tables/aws_config_conformance_pack_rule_compliances.md
  resources/provider/migrations/postgres/27_v0.10.19.down.sql
  resources/provider/migrations/postgres/27_v0.10.19.up.sql
  resources/provider/migrations/timescale/27_v0.10.19.down.sql
  resources/provider/migrations/timescale/27_v0.10.19.up.sql
  resources/provider/provider.go
  resources/services/config/conformance_pack.go
  resources/services/config/conformance_pack_mock_test.go
Labels: feat

#748 chore: One more redaction: dial errors
  client/errors.go
  client/errors_test.go
Labels: ignore-for-release

#738 fix: increase max_retries, update error message and default configuration
  client/config.go
  client/errors.go
  docs/index.md
Labels: fix

#750 fix: Past migrations: aws_ec2_security_group_ip_permission_user_id_group_pairs PK
  resources/provider/migrations/postgres/15_v0.10.0.up.sql
  resources/provider/migrations/postgres/23_v0.10.15.down.sql
  resources/provider/migrations/timescale/15_v0.10.0.up.sql
  resources/provider/migrations/timescale/23_v0.10.15.down.sql
Labels: fix

#754 feat: Fetch shared ec2 images
  client/testing.go
  go.sum
  resources/services/ec2/images.go
  resources/services/ec2/images_mock_test.go
  resources/services/kms/keys.go
Labels: feat

#752 chore: Update WAFv2 Managed Groups to use multiplexer
  resources/services/wafv2/managed_rule_groups.go
  resources/services/wafv2/managed_rule_groups_mock_test.go
  resources/services/wafv2/rule_groups.go
  resources/services/wafv2/rule_groups_mock_test.go
Labels: ignore-for-release

#756 chore: Fix migrations
  resources/provider/migrations/postgres/26_v0.10.18.down.sql
  resources/provider/migrations/postgres/26_v0.10.18.up.sql
  resources/provider/migrations/postgres/27_v0.10.19.down.sql
  resources/provider/migrations/postgres/27_v0.10.19.up.sql
  resources/provider/migrations/timescale/26_v0.10.18.down.sql
  resources/provider/migrations/timescale/26_v0.10.18.up.sql
  resources/provider/migrations/timescale/27_v0.10.19.down.sql
  resources/provider/migrations/timescale/27_v0.10.19.up.sql
Labels: ignore-for-release

#757 chore: Added mq_brokers gen description
  resources/services/mq/brokers.go
  resources/services/mq/gen.hcl
Labels: ignore-for-release

#759 fix: Shared Images Cannot Access LastLaunched
  resources/services/ec2/images.go
  resources/services/ec2/images_mock_test.go
Labels: fix

#764 chore: Add local terraform variables
  terraform/accessanalyzer/local/variables.tf
  terraform/apigateway2/local/variables.tf
  terraform/autoscaling/local/variables.tf
  terraform/backup/local/variables.tf
  terraform/cloudformation/local/variables.tf
  terraform/ec2/local/variables.tf
  terraform/ecs/local/variables.tf
  terraform/iot/local/variables.tf
  terraform/lambda/local/variables.tf
  terraform/mq/local/variables.tf
  terraform/qldb/local/variables.tf
  terraform/rds/local/variables.tf
  terraform/redshift/local/variables.tf
  terraform/s3/local/variables.tf
  terraform/sagemaker/local/variables.tf
  terraform/sns/local/variables.tf
  terraform/sqs/local/variables.tf
  terraform/ssm/local/variables.tf
  terraform/wafregional/local/.terraform.lock.hcl
  terraform/wafregional/local/variables.tf
  terraform/wafv2/local/variables.tf
Labels: ignore-for-release

#760 feat: Added accessanalyzer_analyzers gen description
  docs/tables/aws_access_analyzer_analyzer_finding_sources.md
  docs/tables/aws_access_analyzer_analyzer_findings.md
  docs/tables/aws_access_analyzer_analyzers.md
  go.mod
  go.sum
  resources/provider/provider.go
  resources/services/accessanalyzer/analyzers.go
  resources/services/accessanalyzer/analyzers_mock_test.go
  resources/services/accessanalyzer/gen.hcl
Labels: feat

#761 chore: Ignore local terraform files
  .gitignore
Labels: ignore-for-release

#762 chore(terraform): Add elasticbeanstalk
  terraform/elasticbeanstalk/local/main.tf
  terraform/elasticbeanstalk/local/variables.tf
  terraform/elasticbeanstalk/modules/test/elasticbeanstalk.tf
  terraform/elasticbeanstalk/modules/test/provider.tf
  terraform/elasticbeanstalk/modules/test/terraform.tf
  terraform/elasticbeanstalk/modules/test/variables.tf
  terraform/elasticbeanstalk/prod/.terraform.lock.hcl
  terraform/elasticbeanstalk/prod/main.tf
  terraform/elasticbeanstalk/prod/terraform.tf
Labels: ignore-for-release

#763 chore: Update make file, add db migration script
  Makefile
Labels: ignore-for-release

#793 chore(make-file): Fix `pg-stop` target
  Makefile
Labels: ignore-for-release

#720 feat: Add backup settings
  client/mocks/backup.go
  client/services.go
  docs/tables/aws_backup_global_settings.md
  docs/tables/aws_backup_region_settings.md
  resources/provider/migrations/postgres/26_v0.10.18.down.sql
  resources/provider/migrations/postgres/26_v0.10.18.up.sql
  resources/provider/migrations/timescale/26_v0.10.18.down.sql
  resources/provider/migrations/timescale/26_v0.10.18.up.sql
  resources/provider/provider.go
  resources/services/backup/gen.hcl
  resources/services/backup/global_settings.go
  resources/services/backup/global_settings_mock_test.go
  resources/services/backup/region_settings.go
  resources/services/backup/region_settings_mock_test.go
Labels: feat

#755 fix: Upgrade SDK to return diagnostics in Configure
  client/client.go
  client/testing.go
  go.mod
  go.sum
Labels: fix

#796 fix: Ignore permissions error on backup global settings
  resources/services/backup/global_settings.go
Labels: fix

#798 feat: Classify errors in ConfigureProvider
  client/client.go
  client/errors.go
  go.mod
  go.sum
Labels: feat

#802 fix: Migrations
  resources/provider/migrations/postgres/26_v0.10.18.down.sql
  resources/provider/migrations/postgres/26_v0.10.18.up.sql
  resources/provider/migrations/postgres/27_v0.11.1.down.sql
  resources/provider/migrations/postgres/27_v0.11.1.up.sql
  resources/provider/migrations/timescale/26_v0.10.18.down.sql
  resources/provider/migrations/timescale/26_v0.10.18.up.sql
  resources/provider/migrations/timescale/27_v0.11.1.down.sql
  resources/provider/migrations/timescale/27_v0.11.1.up.sql
Labels: fix

#811 feat: Perform ec2 images calls concurrently
  resources/services/ec2/images.go
Labels: feat
